apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-gateway
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-gateway
  template:
    metadata:
      labels:
        app: client-gateway
    spec:
      containers:
        - name: client-gateway
          image: your-docker-image:qa
          envFrom:
            - secretRef:
                name: client-gateway-secrets
          ports:
            - containerPort: 8000
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 5672
            - containerPort: 15672
